# Generated by Django 4.1.1 on 2022-09-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StorageAdditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('amount', models.IntegerField(verbose_name='Количество')),
                ('unit_measure', models.CharField(max_length=10, verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Склад дополнений',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='StorageFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('amount', models.IntegerField(verbose_name='Количество')),
                ('unit_measure', models.CharField(max_length=10, verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Склад продуктов',
                'ordering': ('name',),
            },
        ),
    ]
