# Generated by Django 4.1.1 on 2022-09-23 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageadditions',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='storagefood',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.CreateModel(
            name='IngredientsFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Количество')),
                ('unit_measure', models.CharField(max_length=10, verbose_name='Единица измерения')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('name_food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indredietsfood', to='cakes.storagefood', verbose_name='Наименование продукта')),
            ],
            options={
                'verbose_name': 'Ингредиенты продуктов',
                'ordering': ('name_food',),
            },
        ),
        migrations.CreateModel(
            name='IngredientsAdditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Количество')),
                ('unit_measure', models.CharField(max_length=10, verbose_name='Единица измерения')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('name_addition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indredietsadditions', to='cakes.storageadditions', verbose_name='Наименование дополнения')),
            ],
            options={
                'verbose_name': 'Ингредиенты дополнений',
                'ordering': ('name_addition',),
            },
        ),
        migrations.CreateModel(
            name='Desserts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('weight', models.PositiveIntegerField(default=0, verbose_name='Вес')),
                ('price', models.FloatField(default=0, verbose_name='Цена')),
                ('ingredients_additions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ing_addinion', to='cakes.ingredientsadditions')),
                ('ingredients_food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ing_food', to='cakes.ingredientsfood')),
            ],
            options={
                'verbose_name': 'Десерт',
                'verbose_name_plural': 'Десерты',
                'ordering': ('name',),
            },
        ),
    ]
