# Generated by Django 4.1.1 on 2022-09-23 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0002_storageadditions_price_storagefood_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desserts',
            name='ingredients_additions',
        ),
        migrations.RemoveField(
            model_name='desserts',
            name='ingredients_food',
        ),
        migrations.AddField(
            model_name='ingredientsadditions',
            name='dessert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ing_addinion', to='cakes.desserts'),
        ),
        migrations.AddField(
            model_name='ingredientsfood',
            name='dessert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ing_food', to='cakes.desserts'),
        ),
    ]
