# Generated by Django 4.1.1 on 2022-09-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0003_remove_desserts_ingredients_additions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desserts',
            name='weight',
            field=models.FloatField(default=0, verbose_name='Вес'),
        ),
    ]
