# Generated by Django 4.1.1 on 2022-09-26 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cakes', '0004_alter_desserts_weight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='desserts',
            options={'ordering': ('name', 'price'), 'verbose_name': 'Десерт', 'verbose_name_plural': 'Десерты'},
        ),
        migrations.RemoveField(
            model_name='ingredientsadditions',
            name='dessert',
        ),
        migrations.RemoveField(
            model_name='ingredientsfood',
            name='dessert',
        ),
        migrations.AddField(
            model_name='desserts',
            name='ing_add',
            field=models.ManyToManyField(related_name='ing_addinion', to='cakes.ingredientsadditions', verbose_name='Список дополнений'),
        ),
        migrations.AddField(
            model_name='desserts',
            name='ing_food',
            field=models.ManyToManyField(related_name='ing_food', to='cakes.ingredientsfood', verbose_name='Ингредиенты продуктов'),
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_wishes', models.TextField(max_length=5000, verbose_name='Дополнительные пожелания')),
                ('phone', models.CharField(default='-', max_length=11, verbose_name='Телефон')),
                ('self_service', models.BooleanField(default=False, help_text='Адрес смотрите в разделе контакты', verbose_name='Самовывоз')),
                ('delivery', models.TextField(help_text='Если вы выбрали сомовывоз, напишите в этом окне время когда вы приедете за заказом', max_length=500, verbose_name='Адрес доставки')),
                ('dessert', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cakes.desserts', verbose_name='Наменование')),
                ('сustomer', models.ForeignKey(on_delete=models.SET('Заказчик'), to=settings.AUTH_USER_MODEL, verbose_name='Заказчик')),
            ],
        ),
        migrations.CreateModel(
            name='Decor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('ing_add', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cakes.ingredientsadditions', verbose_name='Список дополнений')),
                ('ing_food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cakes.ingredientsfood', verbose_name='Ингредиенты продуктов')),
            ],
            options={
                'verbose_name': 'Декор',
                'verbose_name_plural': 'Декоры',
                'ordering': ('name', 'price'),
            },
        ),
    ]
