# Generated by Django 4.1.1 on 2022-09-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0006_remove_desserts_ing_add_remove_desserts_ing_food_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='desserts',
            name='ing_add',
            field=models.ManyToManyField(related_name='ing_addinion', to='cakes.ingredientsadditions', verbose_name='Список дополнений'),
        ),
        migrations.AddField(
            model_name='desserts',
            name='ing_food',
            field=models.ManyToManyField(related_name='ing_food', to='cakes.ingredientsfood', verbose_name='Ингредиенты продуктов'),
        ),
    ]
