# Generated by Django 4.1.1 on 2022-09-26 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0007_desserts_ing_add_desserts_ing_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decor',
            name='ing_add',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cakes.ingredientsadditions', verbose_name='Список дополнений'),
        ),
    ]
