# Generated by Django 4.1.1 on 2022-09-26 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0008_alter_decor_ing_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decor',
            name='ing_food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cakes.ingredientsfood', verbose_name='Ингредиенты продуктов'),
        ),
    ]
