# Generated by Django 4.1.1 on 2022-09-27 11:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0009_alter_decor_ing_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='decor',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=datetime.date(2022, 9, 27), verbose_name='Опубликовано'),
        ),
        migrations.AddField(
            model_name='decor',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/decors/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='decor',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Выводить в списке?'),
        ),
        migrations.AddField(
            model_name='desserts',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=datetime.date(2022, 9, 27), verbose_name='Опубликовано'),
        ),
        migrations.AddField(
            model_name='desserts',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/desserts/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='desserts',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Выводить в списке?'),
        ),
        migrations.AlterField(
            model_name='decor',
            name='ing_add',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ing_decor_add', to='cakes.ingredientsadditions', verbose_name='Список дополнений'),
        ),
        migrations.AlterField(
            model_name='decor',
            name='ing_food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ing_decor_food', to='cakes.ingredientsfood', verbose_name='Ингредиенты продуктов'),
        ),
        migrations.CreateModel(
            name='AdditionalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/add_img/', verbose_name='Изображение')),
                ('decor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cakes.decor', verbose_name='Декор')),
                ('dessert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cakes.desserts', verbose_name='Десерт')),
            ],
            options={
                'verbose_name': 'Дополнительная иллюстрация',
                'verbose_name_plural': 'Дополнительные иллюстрации',
            },
        ),
    ]
