# Generated by Django 4.1.1 on 2022-09-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0010_decor_created_at_decor_image_decor_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decor',
            name='created_at',
            field=models.DateTimeField(db_index=True, default='2022.09.27', verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='desserts',
            name='created_at',
            field=models.DateTimeField(db_index=True, default='2022.09.27', verbose_name='Опубликовано'),
        ),
    ]
