# Generated by Django 4.1.1 on 2022-09-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0011_alter_decor_created_at_alter_desserts_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decor',
            name='created_at',
            field=models.DateTimeField(db_index=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='desserts',
            name='created_at',
            field=models.DateTimeField(db_index=True, verbose_name='Опубликовано'),
        ),
    ]
