# Generated by Django 4.1.1 on 2022-09-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0012_alter_decor_created_at_alter_desserts_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='decor',
            options={'ordering': ('-created_at', 'name', 'price'), 'verbose_name': 'Декор', 'verbose_name_plural': 'Декоры'},
        ),
        migrations.AlterModelOptions(
            name='desserts',
            options={'ordering': ('-created_at', 'name', 'price'), 'verbose_name': 'Десерт', 'verbose_name_plural': 'Десерты'},
        ),
        migrations.AddField(
            model_name='storagefood',
            name='min_amount',
            field=models.IntegerField(default=0, verbose_name='Минимально необходимое количество'),
        ),
    ]
