# Generated by Django 4.1.1 on 2022-09-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0013_alter_decor_options_alter_desserts_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageadditions',
            name='min_amount',
            field=models.IntegerField(default=0, verbose_name='Минимально необходимое количество'),
        ),
    ]
