# Generated by Django 4.1.1 on 2022-09-29 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0014_storageadditions_min_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='filling',
            field=models.CharField(choices=[('Raspberry', 'Малина'), ('Cherry', 'Вишня'), ('Snickers', 'Сникерс')], default='Выберите начинку', max_length=50, verbose_name='Начинка'),
        ),
        migrations.AddField(
            model_name='orders',
            name='img_decor',
            field=models.ImageField(default='-', upload_to='orders', verbose_name='Изображение декора'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='dessert',
            field=models.CharField(choices=[('Торт', (('Pie_1,5_kg', 'Торт - 1,5 кг'), ('Pie_2_kg', 'Торт - 2 кг'), ('Pie_2,5_kg', 'Торт - 2,5 кг'), ('Pie_3_kg', 'Торт - 3 кг'), ('Pie_3,5_kg', 'Торт - 3,5 кг'), ('Pie_4_kg', 'Торт - 4 кг'), ('Pie_4,5_kg', 'Торт - 4,5 кг'), ('Pie_5_kg', 'Торт - 5 кг'), ('Pie_5,5_kg', 'Торт - 5,5 кг'), ('Pie_6_kg', 'Торт - 6 кг'))), ('Бенто торт', (('Bento_рie_550_gr', 'Бенто торт - ~550 гр'), ('Big_bento_pie_800_gr', 'BIG бенто торт - ~800 гр'))), ('Капкейки', (('Cupcakes_6_grand_650_gr', 'Капкейки(6 шт.) - ~650 гр'), ('Cupcakes_9_grand_950_gr', 'Капкейки(9 шт.) - ~950 гр'), ('Cupcakes_12_grand_1300_gr', 'Капкейки(12 шт.) - ~1300 гр'))), ('Трайфлы', (('Trifles_4_grand_800_gr', 'Капкейки(4 шт.) - ~800 гр'), ('Trifles_6_grand_1200_gr', 'Капкейки(6 шт.) - ~1200 гр'), ('Trifles_9_grand_1800_gr', 'Капкейки(9 шт.) - ~1800 гр'), ('Trifles_12_grand_2400_gr', 'Капкейки(12 шт.) - ~2400 гр'))), ('Кейк попсы в виде сердца', (('Cake_pop_heart_4_grand_600_gr', 'Кейк попсы(4 шт.) - ~600 гр'), ('Cake_pop_heart_6_grand_900_gr', 'Кейк попсы(6 шт.) - ~900 гр'), ('Cake_pop_heart_9_grand_1350_gr', 'Кейк попсы(9 шт.) - ~1350 гр'), ('Cake_pop_heart_12_grand_1800_gr', 'Кейк попсы(12 шт.) - ~1800 гр'))), ('Набор (бенто торт или BIG бенто торт + капкейки (5 шт.) или трайфлы (5 шт.))', (('Bento_рie + cupcakes', 'Бенто торт + капкейки'), ('Bento_рie + trifles', 'Бенто торт + трайфлы'), ('Big_bento_pie + cupcakes', 'BIG бенто торт + капкейки'), ('Big_bento_pie + trifles', 'BIG бенто торт + трайфлы')))], default='Выберите десерт', max_length=50, verbose_name='Наменование'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='Телефон'),
        ),
    ]
