# Generated by Django 4.1.1 on 2022-09-29 08:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0015_orders_filling_orders_img_decor_alter_orders_dessert_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Десерт', 'verbose_name_plural': 'Десерты'},
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='сustomer',
            new_name='customer',
        ),
        migrations.AddField(
            model_name='orders',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=datetime.datetime.today, verbose_name='Дата заказа'),
        ),
        migrations.AddField(
            model_name='orders',
            name='datetime_delivery',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата и время доставки или самовывоза'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='delivery',
            field=models.TextField(blank=True, help_text='Данное поле заполняется только если вам нужна доставка, а не самовывоз', max_length=500, null=True, verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='self_service',
            field=models.BooleanField(default=False, help_text='Адрес кондитера смотрите в разделе контакты', verbose_name='Самовывоз?'),
        ),
    ]
