# Generated by Django 4.1.1 on 2022-10-06 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0018_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('dessert', '-created_at'), 'verbose_name': 'Комментарий десерта', 'verbose_name_plural': 'Комментарии десертов'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='dessert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='cakes.desserts', verbose_name='Десерт'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cakes.comment', verbose_name='Родитель'),
        ),
        migrations.CreateModel(
            name='CommentDecor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, verbose_name='Автор')),
                ('content', models.TextField(max_length=1000, verbose_name='Содержание')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Выводить на экран?')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликован')),
                ('decor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_decor', to='cakes.decor', verbose_name='Декор')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cakes.commentdecor', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Комментарий декора',
                'verbose_name_plural': 'Комментарии декоров',
                'ordering': ('decor', '-created_at'),
            },
        ),
    ]
